TestIngressControllerScale: Re-get between updates
Get the ingress controller from the API in between updates so that that
each update uses the latest resource version in order to prevent the
following test failure:

    --- FAIL: TestIngressControllerScale (2.62s)
    	operator_test.go:517: failed to update ingresscontroller: Operation cannot be fulfilled on ingresscontrollers.operator.openshift.io "default": the object has been modified; please apply your changes to the latest version and try again

This commit is related to bug 1705100.

https://bugzilla.redhat.com/show_bug.cgi?id=1705100

* test/e2e/operator_test.go (TestIngressControllerScale): Get the ingress
controller in between updates to ensure we have the latest resource version
for each update.